

rice

eels_on_rice
	
pilaf

chicken-'n'-egg_on_rice

pork_cutlet_on_rice


beef_curry
	
sushi

chicken_rice


fried_rice	

tempura_bowl


bibimbap
	
toast

	croissant


roll_bread

raisin_bread


chip_butty

	hamburger
	
pizza


sandwiches

udon_noodle

tempura_udon

soba_noodle

ramen_noodle

beef_noodle

tensin_noodle

fried_noodle

	spaghetti

Japanese-style_pancake

takoyaki


gratin

sauteed_vegetables

	croquette 

grilled_eggplant!

sauteed_spinach"

vegetable_tempura#

	miso_soup$


potage%

sausage&

oden'


omelet(

	ganmodoki)


jiaozi*

stew+

teriyaki_grilled_fish,


fried_fish-

grilled_salmon.

salmon_meuniere/

sashimi0

grilled_pacific_saury1

sukiyaki2

sweet_and_sour_pork3

lightly_roasted_fish4

steamed_egg_hotchpotch5

tempura6

fried_chicken7

sirloin_cutlet8


nanbanzuke9

boiled_fish:

seasoned_beef_with_potatoes;

hambarg_steak<


beef_steak=


dried_fish>

ginger_pork_saute?

spicy_chili-flavored_tofu@

yakitoriA

cabbage_rollB

rolled_omeletC

egg_sunny-side_upD

fermented_soybeansE

	cold_tofuF

egg_rollG

chilled_noodleH

stir-fried_beef_and_peppersI

simmered_porkJ
!
boiled_chicken_and_vegetablesK

sashimi_bowlL


sushi_bowlM
%
!fish-shaped_pancake_with_bean_jamN

shrimp_with_chill_sourceO

roast_chickenP

steamed_meat_dumplingQ

omelet_with_fried_riceR

cutlet_curryS

spaghetti_meat_sauceT

fried_shrimpU

potato_saladV

green_saladW

macaroni_saladX
'
#Japanese_tofu_and_vegetable_chowderY

pork_miso_soupZ

chinese_soup[

	beef_bowl\
!
kinpira-style_sauteed_burdock]

	rice_ball^

pizza_toast_

dipping_noodles`

hot_doga

french_friesb


mixed_ricec

goya_chanpurud